# dev 環境
[DEV]
WORKER_ACCOUNT = worker
WORKER_PASSWORD = worker
RABBITMQ_HOST = 127.0.0.1
RABBITMQ_PORT = 5672
MYSQL_HOST = 127.0.0.1
MYSQL_PORT = 3306
MYSQL_ACCOUNT = root
MYSQL_PASSWORD = ppWgnb_mfGe2m_
MYSQL_DATABASE = headphone_db


# Docker 環境
[DOCKER]
WORKER_ACCOUNT = worker
WORKER_PASSWORD = worker
RABBITMQ_HOST = rabbitmq
RABBITMQ_PORT = 5672
MYSQL_HOST = mysql
MYSQL_PORT = 3306
MYSQL_ACCOUNT = root
MYSQL_PASSWORD = ppWgnb_mfGe2m_
MYSQL_DATABASE = headphone_db


GCP_PROJECT_ID=cryptic-net-498101-t4
BQ_DATASET=ecommerce
BQ_LOCATION=us-central1
GCS_BUCKET=my-ecommerce-tracker-data-2026


# Prod 環境(未來連雲端環境)
[PRODUCTION]
WORKER_ACCOUNT = worker
WORKER_PASSWORD = worker
RABBITMQ_HOST = rabbitmq
RABBITMQ_PORT = 5672
MYSQL_HOST = mysql
MYSQL_PORT = 3306
MYSQL_ACCOUNT = root
MYSQL_PASSWORD = ppWgnb_mfGe2m_
MYSQL_DATABASE = headphone_db
