version: '3.0'  # 使用 Docker Compose 的版本 3.0，適合大部分部署場景

services:
  crawler_pchome: 
    image: my-crawler:${DOCKER_IMAGE_VERSION}  # 更新image 版本
   
    hostname: "docker-pchome"
    
    command: uv run --env-file=.env celery -A crawler.worker worker -Q pchome_q -c 4 --hostname=celery@%h --loglevel=info
    
    restart: always  
    environment:
      - TZ=Asia/Taipei  # 設定時區為台北（UTC+8）
    networks:
      - dev_network # 連到新網路

  crawler_momo:
    image: my-crawler:${DOCKER_IMAGE_VERSION}
    hostname: "docker-momo"
    command: uv run --env-file=.env celery -A crawler.worker worker -Q momo_q -c 1 --hostname=celery@%h --loglevel=info
    
    restart: always  # 若容器停止或崩潰，自動重新啟動
    environment:
       - TZ=Asia/Taipei 
    networks:
      - dev_network 

networks:
  dev_network:
    external: true
